2개(0,1)인 2진분류가 아니라 2개이상인 다중분류ex(학점 a,b,c)

In [3]:
import numpy as np

In [2]:
def fn(x):
    print(x/sum(x))

In [8]:
a = np.array([2.0,1.0,0.1])
fn(a)
softmax(a)

[0.64516129 0.32258065 0.03225806]
[7.3890561  2.71828183 1.10517092]
[0.65900114 0.24243297 0.09856589]


In [9]:
def softmax(x):
    e = np.exp(x)
    print(e)
    print( e/np.sum(e) )

NameError: name 'train_test_split' is not defined