In [4]:
import numpy as np 
import pandas as pd 
import seaborn as sb 
import matplotlib.pyplot as plt
import mglearn
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression


import warnings
warnings.simplefilter('ignore')


In [100]:
model_logi.score(x_data, y_data)

1.0

In [5]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]])
y_data = np.array( [[0],[1],[1],[0]])


In [117]:
# model_logi = LogisticRegression(max_iter =1000, verbose = 1)
# hidden_layer_sizes = (200,10) 2차원으로 값을 주면 히든레이어갯수는 2개 
# model_logi.coefs_ 의 개수 -1 = 히든레이어의 개수 h1,h2,h3,... -1인이유는 아웃풋레이어가 하나 포함된다
# solver = optimizrer 

# alpha = running rate
# max_iter  = 학습횟수
model_logi = MLPClassifier(hidden_layer_sizes = (100))
model_logi.fit(x_data, y_data)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=100, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [118]:
model_logi.predict([[0,1]])

array([1])

In [119]:
len(model_logi.coefs_) 

2

In [121]:
model_logi.coefs_[0].shape

(2, 100)

In [122]:
model_logi.coefs_[1].shape

(100, 1)

In [145]:
# 활성함수 layer층은 relu를 통과
# output sigmoid통과
a = np.matmul(x_data,model_logi.coefs_[0])+model_logi.intercepts_[0]
a = relu(a)
b = np.matmul(a,model_logi.coefs_[1])+model_logi.intercepts_[1]
sigmoid(b)

array([[0.34773662],
       [0.65727338],
       [0.65566708],
       [0.34139037]])

In [130]:
b

array([[ 0.28917233],
       [ 0.07277893],
       [-0.13331321],
       [-0.34970661]])

In [127]:
model_logi.coefs_[1].shape

(100, 1)

In [104]:
model_logi.coefs_[2].shape

(10, 9)

In [105]:
model_logi.coefs_[3].shape

(9, 4)

In [106]:
model_logi.coefs_[4].shape

(4, 1)

In [25]:
model_logi.coefs_[0]. shape
# (2,100) 2는 특성데이터 개수

(2, 100)

In [102]:
# ndarray2개가 리스트안에 들어가있음
len(model_logi.coefs_)

5

In [101]:
# xor게이트를 예측 불가능
model_logi.predict( x_data )

array([0, 1, 1, 0])

In [ ]:
# hidden layer size = (100,)

In [29]:
model_logi.coefs_[1].shape

(100, 1)

In [24]:
len(model_logi.intercepts_)

100

In [26]:
model_logi.intercepts_[0].shape

(100,)

In [30]:
model_logi.intercepts_[1].shape

(1,)

In [37]:
import math

In [132]:
def sigmoid(z):
    return 1/(1+math.e**-z)

In [42]:
def relu(x):
    return np.maximum(0, x)

In [54]:
a=np.matmul(x_data,model_logi.coefs_[0])+model_logi.intercepts_[0]
print(a)
b = np.matmul(a,model_logi.coefs_[1])+model_logi.intercepts_[1]
b

[[-2.35793387e-01  1.38170153e-01  1.93354152e-01  1.90937902e-01
  -8.98051965e-02 -3.81579776e-04 -1.85135064e-01  1.23319260e-01
  -6.60076143e-02 -2.32114771e-01 -1.05467230e-01 -7.25884779e-02
  -2.08434047e-01  2.74472461e-04  2.67540991e-01 -1.61529793e-01
  -2.31226530e-01  5.94671253e-02 -5.95286070e-04 -1.62363904e-01
  -7.70439403e-02 -2.31621309e-01 -2.56754872e-01 -7.02460686e-03
  -1.58081754e-01 -1.39746088e-01 -1.83305891e-01  7.51735577e-02
  -8.95822676e-04 -4.17404848e-02 -1.56809002e-03 -1.76260392e-01
  -1.54974081e-01 -8.44417495e-03  1.67751485e-01  1.02844895e-01
  -7.70412075e-04  6.84986136e-02  1.39115477e-01  2.86839624e-01
  -8.19610665e-02 -2.79895076e-01  1.08665295e-01  4.12153373e-02
   2.35522747e-01 -2.57083486e-01 -1.19898201e-01 -2.57898971e-01
   1.62943723e-01  3.88787481e-02  1.77473470e-01 -3.39592877e-02
   2.58816677e-01 -1.68365268e-01  1.88546265e-01  2.17717764e-01
  -6.94784141e-04 -1.62986417e-01  7.91884530e-02  1.60163866e-01
   1.41883

array([[-0.00051245],
       [-0.05314564],
       [-0.0058566 ],
       [-0.0584898 ]])

In [53]:
d=relu(a)
d[0]

array([0.00000000e+00, 1.38170153e-01, 1.93354152e-01, 1.90937902e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.23319260e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.74472461e-04, 2.67540991e-01, 0.00000000e+00,
       0.00000000e+00, 5.94671253e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.51735577e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.67751485e-01, 1.02844895e-01,
       0.00000000e+00, 6.84986136e-02, 1.39115477e-01, 2.86839624e-01,
       0.00000000e+00, 0.00000000e+00, 1.08665295e-01, 4.12153373e-02,
       2.35522747e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.62943723e-01, 3.88787481e-02, 1.77473470e-01, 0.00000000e+00,
       2.58816677e-01, 0.00000000e+00, 1.88546265e-01, 2.17717764e-01,
      

In [ ]:
특성데이터가 2개일경우 라벨이1개인경우
<>괄호 = 히든레이어
? !  = 하이퍼파라미터 (자기가 정하는 숫자)
4 x 2 (matmul) <2(특성) x ?   (matmul) ? x !  (matmul) ! x 1(라벨) > 
4 x 2 (matmul) <2(특성) x 10   (matmul) 10 x 20  (matmul) 20 x 1(라벨) > 
?개수만큼 bias(intercept)가 나온다


히든레이어가 너무많으면 오히려 학습효과가 떨어지는 배니싱현상
배니싱현상을 막기위해서 렐루 함수를 사용한다